### ISSUE TITLE
Extract N keyframes

### ISSUE THREAD

**Issue by edoardop13** [averdones/video-kf#1]
Hi, is it possible to extract only N keyframes and not all?

**Comment by averdones** [comment]
Right now, that option is not implemented. 

It is not clear how to choose N keyframes out of all the iframes extracted by ffmpeg. Some sort of weighting strategy should be implemented. 

However, I can think of a very naive one which would be simply to select the N evenly spaced out frames in the array of total extracted frames. I don't know how meaningful these frames would be though, but it could be a start.

You could use something like this (**Be careful, this code removes the unwanted frames from KEYFRAMES_DIR**).

```python
from pathlib import Path
import numpy as np

def select_n_frames(keyframes_dir, N):
    all_frames = [x for x in Path(keyframes_dir).iterdir()]
    all_frames.sort(key=lambda fname: int(str(fname).split('\\')[-1].split('.')[0]))

    idx_keep = set(np.linspace(0, len(all_frames) - 1, N, dtype=int))
    idx_remove = set(range(len(all_frames))) - idx_keep
    for i in idx_remove:
        all_frames[i].unlink()

select_n_frames(KEYFRAMES_DIR, N=5)
```

**Comment by edoardop13** [comment]
Thanks!
